name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🧰 Maintenance'
    label: 'chore'
  - title: '⛓️ Dependency update'
    label: 'dependencies'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
exclude_labels:
  - 'build'
  - 'ci'
  - 'refactor'
template: |
  ## Changes

  $CHANGES

autolabeler:
  - label: 'enhancement'
    title:
      - '/^feat!?:.*/'
  - label: 'bug'
    title:
      - '/^fix!?:.*/'
  - label: 'refactor'
    title:
      - '/^(refactor|style)!?:.*/'
  - label: 'build'
    title:
      - '/^build!?:.*/'
  - label: 'ci'
    title:
      - '/^ci!?:.*/'
  - label: 'chore'
    title:
      - '/^(chore|docs)!?:.*/'
